my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_view


urlpatterns = [
    path('', home_view),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls', namespace='polls')),
]

my_blog/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
   path('', views.question_list, name='question_list'),
   path('<int:question_id>/', views.question_detail, name='question_detail'),
   path('new/', views.question_add, name='question_add'),
   path('<int:question_id>/new/', views.choice_add, name='choice_add')
]

my_blog/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    is_open_question = models.BooleanField(default=False)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=200)
    number_of_appearances = models.IntegerField(default=1)

my_blog/polls/forms.py
from django import forms
from django.forms.widgets import DateInput

from .models import Question, Choice


class QuestionForm(forms.ModelForm):
   class Meta:
       model = Question
       fields = '__all__'
       widgets = {
           'pub_date': DateInput(attrs={'type': 'date'}),
       }


class ChoiceForm(forms.ModelForm):
   class Meta:
       model = Choice
       # model = Choice
       fields = '__all__'
       # widgets = {
       #     'pub_date': DateInput(attrs={'type': 'date'}),
       # }

my_blog/my_blog/views.py
from django.shortcuts import render

def home_view(request):
    return render(request, 'home.html')

my_blog/polls/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question
from django.urls import reverse
from django.http import HttpResponseRedirect
from .forms import QuestionForm, ChoiceForm


def question_add(request):
   if request.method == 'POST':
       form = QuestionForm(request.POST)

       if form.is_valid():
           form.save()
           return HttpResponseRedirect(reverse('polls:question_list'))

   else:
       form = QuestionForm()
       return render(request, 'polls/question_form.html', {'form': form})


def choice_add(request, question_id):
   if request.method == 'POST':
       data = request.POST
       form = ChoiceForm(data)
       if form.is_valid():
           form.save()
           return HttpResponseRedirect(reverse('polls:question_detail', kwargs={'question_id': question_id}))

   else:
       form = ChoiceForm(initial={'question': question_id})
       return render(request, 'polls/choice_form.html', {'form': form, 'question_id': question_id})


def question_list(request):
    questions = Question.objects.all()
    return render(request, 'polls/question_list.html', {'questions': questions})


def question_detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/question_detail.html', {'question': question})

my_blog/polls/templates/polls/question_detail.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>{{ question.question_text }}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <table>
        <tr>
            <th>odp</th>
            <th>głosy</th>
        </tr>
    {% for choice in question.choice_set.all %}
        <tr>
            <td>{{ choice.choice_text }}</td>
            <td>{{ choice.votes }}</td>
        </tr>
    {% endfor %}
    </table>
</body>
</html>

my_blog/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sweet Home Albama</title>
</head>
<body>
    <h1>Home</h1>
    {% if user.is_authenticated %}
    witaj,
    {{ request.user }}
    {% else %}
    nie jestes zalogowany
    {% endif %}
    <a href="http://127.0.0.1:8000/polls">polls</a>
</body>
</html>

my_blog/templates/polls/choice_form.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Nowe Wybór</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
<h2>Dodaj nowe wybór</h2>
<form method="post">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="submit" value="Zapisz">
</form>
<a href="{% url 'polls:question_detail' question_id %}">Anuluj</a>
</body>

</html>

my_blog/templates/polls/question_detail.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>{{ question.question_text }}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <table>
        <tr>
            <th>odp</th>
            <th>głosy</th>
        </tr>
    {% for choice in question.choices.all %}
        <tr>
            <td>{{ choice.choice_text }}</td>
            <td>{{ choice.votes }}</td>
        </tr>
    {% endfor %}
    </table>
    <a href="{% url 'polls:choice_add' question.id %}">Dodaj nowe wybór</a>
    <a href="{% url 'polls:question_list'%}">Cofnij</a>
</body>
</html>

my_blog/templates/polls/question_form.html
{% load static %}
<link rel="stylesheet" href="{% static 'styles.css' %}">

<h2>Dodaj nowe pytanie</h2>
<form method="post">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="submit" value="Zapisz">
</form>

my_blog/templates/polls/question_list.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>niewiem</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<h1>Moje Super Świetne Pytania :)</h1>
<h4>Ładne style to pojęcie względne</h4>
<div>
    <table>
        <tr>
            <th>ID</th>
            <th>Pytanie</th>
            <th>Data Opublikowania</th>
            <th>Typ Pytania</th>
        </tr>
   {% for question in questions %}
       <tr>
           <td>{{ question.id }}</td>
           <td><a href="{% url 'polls:question_detail' question.id %}"> {{ question.question_text }} </a></td>
           <td>{{ question.pub_date }}</td>
           {% if question.is_open_question %}
                <td>Otwarte</td>
           {% else %}
                <td>Zamknięte</td>
           {% endif %}
       </tr>
   {% endfor %}
    </table>
    <a href="{% url 'polls:question_add' %}">Dodaj nowe pytanie</a>
</div>
</body>
</html>